DROP TABLE IF EXISTS `users`;

CREATE TABLE users (
    `id` INTEGER PRIMARY KEY AUTOINCREMENT,
    `username` VARCHAR(255) UNIQUE NULL,
    `email` VARCHAR(255) UNIQUE NOT NULL,
    `password` VARCHAR(120) NOT NULL,
    `is_admin` BOOLEAN DEFAULT 0 NOT NULL
);